### ISSUE TITLE
References

### ISSUE THREAD

**Issue by tkipf** [shagunsodhani/pregel#5]
Nice and clean re-implementation! I would appreciate if you could refer to some of the original work:

https://github.com/tkipf/gcn
https://arxiv.org/abs/1609.02907

```
@article{kipf2016semi,
  title={Semi-Supervised Classification with Graph Convolutional Networks},
  author={Kipf, Thomas N and Welling, Max},
  journal={arXiv preprint arXiv:1609.02907},
  year={2016}
}
```

Thanks!

**Comment by shagunsodhani** [comment]
Added references to both the papers and implementations :)
